# Example requests for VS Code REST Client extension
# https://marketplace.visualstudio.com/items?itemName=humao.rest-client

@baseUrl = http://localhost:3000/api

@authorization = csukaey6h8t4sxwdt7fhxcxqindj0mzx0pkek43r


# GIFT REQUESTS

###
GET {{baseUrl}}/gifts

###
GET {{baseUrl}}/gifts/e7051758-f907-4ebf-bcaf-5b26b3198409

###
POST {{baseUrl}}/gifts
Content-Type: application/json

{
  "receiver": "Aku Ankka",
  "gift": "Kortti"
}

###
PATCH {{baseUrl}}/gifts/e7051758-f907-4ebf-bcaf-5b26b3198409
Content-Type: application/json

{
  "receiver": "Aku Ankka",
  "gift": "Kortti"
}

###
PUT {{baseUrl}}/gifts/e7051758-f907-4ebf-bcaf-5b26b3198409
Content-Type: application/json

{
  "receiver": "Aku Ankka",
  "gift": "Kortti"
}

###
DELETE {{baseUrl}}/gifts/e7051758-f907-4ebf-bcaf-5b26b3198409


# USER REQUESTS

###
GET {{baseUrl}}/users
Authorization: {{authorization}}
Origin: {{baseUrl}}

###
GET {{baseUrl}}/users/26ab195c-5f56-4831-bedd-07725e8012ff
Authorization: {{authorization}}
Origin: {{baseUrl}}


###
POST {{baseUrl}}/users
Content-Type: application/json
Authorization: {{authorization}}
Origin: {{baseUrl}}

{
  "email": "john.doe@doemail.com",
  "firstName": "John",
  "lastName": "Doe",
  "password": "AlwaysHashThePasswordAndNeverUsePlainText"
}

###
PATCH {{baseUrl}}/users/80934be5-6bb8-4861-8e92-8df8a1dca713
Content-Type: application/json
Authorization: {{authorization}}
Origin: {{baseUrl}}

{
  "email": "matti.meikalainen@esimerkkimail.com",
  "firstName": "Matti",
  "lastName": "Meikäläinen"
}

###
PUT {{baseUrl}}/users/80934be5-6bb8-4861-8e92-8df8a1dca713
Content-Type: application/json
Authorization: {{authorization}}
Origin: {{baseUrl}}

{
  "email": "matti.meikalainen@esimerkkimail.com",
  "firstName": "Mikko",
  "lastName": "Meikäläinen"
}

###
DELETE {{baseUrl}}/users/80934be5-6bb8-4861-8e92-8df8a1dca713
Authorization: {{authorization}}
Origin: {{baseUrl}}

