# Example requests for VS Code REST Client extension
# https://marketplace.visualstudio.com/items?itemName=humao.rest-client

@baseUrl = http://localhost:3000/api

# GIFT REQUESTS

###
GET {{baseUrl}}/gifts

###
GET {{baseUrl}}/gifts/e7051758-f907-4ebf-bcaf-5b26b3198409

###
POST {{baseUrl}}/gifts
Content-Type: application/json

{
  "receiver": "Aku Ankka",
  "gift": "Kortti"
}

###
PATCH {{baseUrl}}/gifts/e7051758-f907-4ebf-bcaf-5b26b3198409
Content-Type: application/json

{
  "receiver": "Aku Ankka",
  "gift": "Kortti"
}

###
PUT {{baseUrl}}/gifts/e7051758-f907-4ebf-bcaf-5b26b3198409
Content-Type: application/json

{
  "receiver": "Aku Ankka",
  "gift": "Kortti"
}

###
DELETE {{baseUrl}}/gifts/e7051758-f907-4ebf-bcaf-5b26b3198409


# USER REQUESTS

###
GET {{baseUrl}}/users

###
GET {{baseUrl}}/users/26ab195c-5f56-4831-bedd-07725e8012ff

###
POST {{baseUrl}}/users
Content-Type: application/json

{
  "email": "john.doe@doemail.com",
  "firstName": "John",
  "lastName": "Doe",
  "password": "AlwaysHashThePasswordAndNeverUsePlainText"
}

###
PATCH {{baseUrl}}/users/26ab195c-5f56-4831-bedd-07725e8012ff
Content-Type: application/json

{
  "email": "matti.meikalainen@esimerkkimail.com",
  "firstName": "Matti",
  "lastName": "Meikäläinen"
}

###
PUT {{baseUrl}}/users/26ab195c-5f56-4831-bedd-07725e8012ff
Content-Type: application/json

{
  "email": "matti.meikalainen@esimerkkimail.com",
  "firstName": "Matti",
  "lastName": "Meikäläinen"
}

###
DELETE {{baseUrl}}/users/26ab195c-5f56-4831-bedd-07725e8012ff

###
GET {{baseUrl}}/users
Authorization: 547pxtzgo4r9kkas5wy0k4fck5a375yhne7sqz6m
NODE_ENV: development

