# Example requests for VS Code REST Client extension
# https://marketplace.visualstudio.com/items?itemName=humao.rest-client

@baseUrl = http://localhost:3000/api

# LOGIN

###
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "john.doe@doemail.com",
  "password": "AlwaysHashThePasswordAndNeverUsePlainText",
  "rememberMe": false
}

# REGISTER

###
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "email": "john.doe@doemail.com",
  "firstName": "John",
  "lastName": "Doe",
  "password": "Password123!"
}


# GIFT REQUESTS

# this triple hashtag (#) has been added so Register request works
###
@giftUUID = cba86307-8f50-4038-bc79-c05cef4fafc1

###
GET {{baseUrl}}/gifts

###
GET {{baseUrl}}/gifts/{{giftUUID}}

###
POST {{baseUrl}}/gifts
Content-Type: application/json

{
  "receiver": "Aku Ankka",
  "gift": "Kortti"
}

###
PATCH {{baseUrl}}/gifts/{{giftUUID}}
Content-Type: application/json

{
  "receiver": "Aku Ankka",
  "gift": "Kortti"
}

###
PUT {{baseUrl}}/gifts/{{giftUUID}}
Content-Type: application/json

{
  "receiver": "Aku Ankka",
  "gift": "Kortti"
}

###
DELETE {{baseUrl}}/gifts/{{giftUUID}}


# USER REQUESTS

@userUUID = 26ab195c-5f56-4831-bedd-07725e8012ff

###
GET {{baseUrl}}/users

###
GET {{baseUrl}}/users/{{userUUID}}


###
POST {{baseUrl}}/users
Content-Type: application/json

{
  "email": "john.doe@doemail.com",
  "firstName": "John",
  "lastName": "Doe",
  "password": "AlwaysHashThePasswordAndNeverUsePlainText"
}

###
PATCH {{baseUrl}}/users/{{userUUID}}
Content-Type: application/json

{
  "email": "matti.meikalainen@esimerkkimail.com",
  "firstName": "Matti",
  "lastName": "Meikäläinen"
}

###
PUT {{baseUrl}}/users/{{userUUID}}
Content-Type: application/json

{
  "email": "matti.meikalainen@esimerkkimail.com",
  "firstName": "Mikko",
  "lastName": "Meikäläinen"
}

###
DELETE {{baseUrl}}/users/{{userUUID}}


# FEEDBACK REQUESTS

###
POST {{baseUrl}}/feedback
Content-Type: application/json

{
  "feedbackText": "Hello world!"
}

# PERSON REQUESTS



@personUUID = ef6bec60-cf63-42d9-a3c7-34ff801411e5

###
GET {{baseUrl}}/persons

###
GET {{baseUrl}}/persons/{{personUUID}}

###
POST {{baseUrl}}/persons
Content-Type: application/json

{
  "name": "John Doe",
  "sendReminders": true
}

###
PATCH {{baseUrl}}/persons/{{personUUID}}
Content-Type: application/json

{
  "email": "matti.meikalainen@esimerkkimail.com",
  "firstName": "Matti",
  "lastName": "Meikäläinen"
}

###
PUT {{baseUrl}}/persons/{{personUUID}}
Content-Type: application/json

{
  "email": "matti.meikalainen@esimerkkimail.com",
  "firstName": "Mikko",
  "lastName": "Meikäläinen"
}

###
DELETE {{baseUrl}}/persons/{{personUUID}}